---
- name: Install ruby-dev
  apt: name=ruby-dev
  sudo: True
- name: Install ureadahead
  apt: name=ureadahead
  sudo: True
- name: Install libyaml
  apt: name=libyaml-dev
  sudo: True
- name: Install binutils
  apt: name=binutils-doc
  sudo: True
- name: Allow access on port 80
  ufw: proto=tcp port=80 rule=allow
- name: Allow access on port 443
  ufw: proto=tcp port=443 rule=allow
